# schema https://docs.jj-vcs.dev/latest/config-schema.json
[user]
name = "..."
email = "..."

[ui]
editor = "nvim"

[aliases]
ls = ["log"]
evolve = ["rebase", "-d", "trunk()", "--skip-emptied"]
evolve-all = ["rebase", "-s", "roots(mutable()~trunk()::~empty())", "-d", "trunk()", "--skip-emptied"]
push = ["util", "exec", "--", "sh", "-c", "jj bookmark set main -r @ && jj git push -b main && jj new"]
fetch = ["util", "exec", "--", "sh", "-c", "jj git fetch && jj rebase -s 'roots(mutable()~trunk()::~empty())' -d 'trunk()' --skip-emptied"]
