# 1. Fix Colors: Enable 24-bit color (needed for Neovim themes)
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# 2. Change Prefix: Ctrl+b is awkward. Let's change it to Ctrl+a (like GNU Screen)
unbind C-b
set -g prefix C-a
bind C-a send-prefix # if there's a program inside tmux that also uses Ctrl+a, pressing it twice will pass thru a cmd

# 3. Mouse Support: Allow clicking tabs and resizing panes with mouse
set -g mouse on

# 4. Vim-like Pane Navigation (h, j, k, l)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# 5. Easy Config Reload (Press Ctrl+a then r)
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# 6. Open new windows/splits in the CURRENT directory (default is home)
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# allow applications inside tmux to set the system clipboard
set -s set-clipboard on
